-- Collegiate Vendas / Operação Sexta Marcha
create extension if not exists pgcrypto;

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.operators (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  codename text not null,
  title text not null default 'Executivo de Vendas',
  team_id uuid references public.teams(id) on delete set null,
  avatar_path text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'executive' check (role in ('admin','manager','executive')),
  active boolean not null default true,
  team_id uuid references public.teams(id) on delete set null,
  operator_id uuid unique references public.operators(id) on delete set null,
  selected_loadout text not null default 'assault',
  avatar_path text,
  avatar_crop jsonb not null default '{"zoom":1.25,"x":0,"y":0}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  subtitle text,
  target_vgv numeric(14,2) not null default 0,
  start_date date not null,
  end_date date not null,
  active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  operator_id uuid not null references public.operators(id) on delete cascade,
  development text not null,
  unit text,
  customer_name text,
  vgv numeric(14,2) not null check (vgv >= 0),
  commission_rate numeric(7,5) not null default 0.03,
  status text not null default 'pending' check (status in ('pending','signed','cancelled')),
  signed_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.loadouts (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  name text not null,
  tagline text,
  description text,
  stats jsonb not null default '[1,1,1,0]'::jsonb,
  sort_order int not null default 0,
  active boolean not null default true
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists sales_campaign_idx on public.sales(campaign_id);
create index if not exists sales_operator_idx on public.sales(operator_id);
create index if not exists sales_signed_at_idx on public.sales(signed_at);
create index if not exists profiles_team_idx on public.profiles(team_id);
create index if not exists operators_team_idx on public.operators(team_id);

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$ select role from public.profiles where id = auth.uid() $$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.teams enable row level security;
alter table public.operators enable row level security;
alter table public.profiles enable row level security;
alter table public.campaigns enable row level security;
alter table public.sales enable row level security;
alter table public.loadouts enable row level security;
alter table public.audit_logs enable row level security;

-- Read access for signed-in users.
create policy "authenticated read teams" on public.teams for select to authenticated using (true);
create policy "authenticated read operators" on public.operators for select to authenticated using (true);
create policy "authenticated read campaigns" on public.campaigns for select to authenticated using (true);
create policy "authenticated read sales" on public.sales for select to authenticated using (true);
create policy "authenticated read loadouts" on public.loadouts for select to authenticated using (true);

-- Profiles: own profile, plus managers/admins can list the team/users.
create policy "read own or managed profiles" on public.profiles for select to authenticated
using (id = auth.uid() or public.current_role() in ('admin','manager'));
create policy "update own profile" on public.profiles for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

-- Admin/manager writes for operational content.
create policy "management write teams" on public.teams for all to authenticated
using (public.current_role() in ('admin','manager')) with check (public.current_role() in ('admin','manager'));
create policy "management write operators" on public.operators for all to authenticated
using (public.current_role() in ('admin','manager')) with check (public.current_role() in ('admin','manager'));
create policy "management write campaigns" on public.campaigns for all to authenticated
using (public.current_role() in ('admin','manager')) with check (public.current_role() in ('admin','manager'));
create policy "management write sales" on public.sales for all to authenticated
using (public.current_role() in ('admin','manager')) with check (public.current_role() in ('admin','manager'));
create policy "admin write loadouts" on public.loadouts for all to authenticated
using (public.current_role() = 'admin') with check (public.current_role() = 'admin');
create policy "management read audit" on public.audit_logs for select to authenticated
using (public.current_role() in ('admin','manager'));

-- Public views are still protected by underlying RLS because security_invoker is enabled.
create or replace view public.campaign_summary
with (security_invoker = true)
as
select
  c.id as campaign_id,
  c.name,
  c.target_vgv,
  coalesce(sum(s.vgv) filter (where s.status = 'signed'),0)::numeric as confirmed_vgv,
  coalesce(sum(s.vgv) filter (where s.status = 'pending'),0)::numeric as pending_vgv,
  coalesce(sum(s.vgv) filter (where s.status in ('signed','pending')),0)::numeric as total_vgv,
  count(*) filter (where s.status = 'signed')::int as signed_contracts,
  count(*) filter (where s.status in ('signed','pending'))::int as total_sales,
  count(*) filter (where s.status in ('signed','pending'))::int as total_units,
  count(distinct s.operator_id) filter (where s.status = 'signed')::int as decorated_operators,
  (select count(*)::int from public.operators o where o.active) as active_operators
from public.campaigns c
left join public.sales s on s.campaign_id = c.id and s.status <> 'cancelled'
where c.active = true
group by c.id, c.name, c.target_vgv;

create or replace view public.operator_performance
with (security_invoker = true)
as
select
  o.id,
  o.full_name,
  o.codename,
  o.title,
  t.name as team_name,
  coalesce(p.avatar_path, o.avatar_path) as avatar_path,
  coalesce(p.selected_loadout, 'assault') as selected_loadout,
  coalesce(sum(s.vgv) filter (where s.status = 'signed'),0)::numeric as vgv,
  count(s.id) filter (where s.status = 'signed')::int as sales_count,
  count(s.id) filter (where s.status = 'signed')::int as units_count,
  case when count(s.id) filter (where s.status='signed') > 0 then 'signed'
       when count(s.id) filter (where s.status='pending') > 0 then 'wait'
       else 'field' end as status
from public.operators o
left join public.teams t on t.id = o.team_id
left join public.profiles p on p.operator_id = o.id
left join public.sales s on s.operator_id = o.id
  and s.campaign_id = (select id from public.campaigns where active = true order by start_date desc limit 1)
  and s.status <> 'cancelled'
where o.active = true
group by o.id, o.full_name, o.codename, o.title, t.name, p.avatar_path, o.avatar_path, p.selected_loadout;

grant select on public.campaign_summary, public.operator_performance to authenticated;

-- Avatar storage bucket.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars','avatars',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

create policy "public avatar reads" on storage.objects for select using (bucket_id = 'avatars');
create policy "users upload own avatar" on storage.objects for insert to authenticated
with check (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users update own avatar" on storage.objects for update to authenticated
using (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users delete own avatar" on storage.objects for delete to authenticated
using (bucket_id='avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Loadout presets.
insert into public.loadouts(key,name,tagline,description,stats,sort_order) values
('assault','Assalto','Agressividade','Ritmo alto, presença e fechamento.','[1,1,1,0]',1),
('sniper','Precisão','Negociação','Foco em conversão de oportunidades qualificadas.','[1,1,0,0]',2),
('recon','Recon','Inteligência','Cadência, leitura de funil e prospecção.','[1,1,1,1]',3),
('support','Suporte','Equipe','Trabalho coordenado e força coletiva.','[1,0,1,1]',4)
on conflict (key) do update set name=excluded.name, tagline=excluded.tagline, description=excluded.description, stats=excluded.stats, sort_order=excluded.sort_order;

-- Seed operation content, idempotent by names.
insert into public.teams(name,slug) values
('Time Alfa','alfa'),('Time Bravo','bravo'),('Time Charlie','charlie'),('Time Delta','delta')
on conflict (slug) do nothing;

insert into public.campaigns(name,subtitle,target_vgv,start_date,end_date,active)
select 'Operação Sexta Marcha','Disciplina. Estratégia. Execução. Juntos por um único objetivo: acelerar resultados.',7000000,'2026-09-01','2026-09-30',true
where not exists (select 1 from public.campaigns where name='Operação Sexta Marcha');

insert into public.operators(full_name,codename,title,team_id)
select v.full_name,v.codename,v.title,(select id from public.teams where slug=v.team_slug)
from (values
('Lucas Costa','FÚRIA','Líder de Esquadrão','bravo'),
('Pedro Augusto','TITÃ','Ponta de Lança','delta'),
('Lucas Silva','PANTERA','Atirador de Elite','alfa'),
('Geovanne','FALCÃO','Assalto','alfa'),
('Yuri','CORVO','Reconhecimento','charlie'),
('Cleiton','AÇO','Suporte Pesado','charlie'),
('Daniel Tonelli','LOBO','Assalto','bravo'),
('Roger','VÍBORA','Batedor','delta'),
('Jean','ÁGUIA','Demolições','alfa'),
('Gustavo Fonseca','BRAVO','Suporte','bravo'),
('Pedro Bastos','ADAGA','Infiltração','charlie'),
('Aron','SENTINELA','Vigia','alfa'),
('Luiz Otávio','TROVÃO','Artilharia','delta'),
('Hércules','GALO','Linha de Frente','alfa')
) as v(full_name,codename,title,team_slug)
where not exists (select 1 from public.operators o where o.full_name=v.full_name);

-- Seed signed/pending VGV from the original campaign dataset.
with c as (select id from public.campaigns where name='Operação Sexta Marcha' limit 1),
vals(full_name,vgv,status,dev,unit) as (values
('Lucas Costa',1955060::numeric,'signed','Uberaba III','Múltiplas'),
('Pedro Augusto',1510160,'signed','Uberaba III','Múltiplas'),
('Lucas Silva',476000,'signed','31 de Março','Múltiplas'),
('Geovanne',439800,'signed','Uberaba II','Múltiplas'),
('Yuri',425800,'signed','31 de Março','Múltiplas'),
('Cleiton',275000,'signed','Uberaba III','Múltiplas'),
('Daniel Tonelli',224900,'signed','31 de Março','Múltiplas'),
('Roger',184900,'signed','31 de Março','Múltiplas'),
('Jean',800218,'pending','Bauru','Standby'),
('Gustavo Fonseca',254704,'pending','Bauru','Standby')
)
insert into public.sales(campaign_id,operator_id,development,unit,customer_name,vgv,status,signed_at)
select c.id,o.id,v.dev,v.unit,'Operação Sexta Marcha',v.vgv,v.status,case when v.status='signed' then '2026-09-17'::date else null end
from vals v join public.operators o on o.full_name=v.full_name cross join c
where not exists (
  select 1 from public.sales s where s.campaign_id=c.id and s.operator_id=o.id and s.vgv=v.vgv and s.status=v.status
);
